name: Node.js

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }} 

    - name: Install Dependencies
      run: npm install

    - name: Lint Codebase
      run: npm run lint

    - name: Execute Tests  
      run: npm run test 
      env:
        CI: true

    - name: Build Project
      run: npm run build